# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: worker.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cworker.proto\"\x16\n\x05Label\x12\r\n\x05value\x18\x01 \x01(\t\"\x19\n\x08Response\x12\r\n\x05value\x18\x01 \x01(\t2@\n\x06Worker\x12\x1a\n\x03max\x12\x06.Label\x1a\t.Response\"\x00\x12\x1a\n\x03min\x12\x06.Label\x1a\t.Response\"\x00\x62\x06proto3')



_LABEL = DESCRIPTOR.message_types_by_name['Label']
_RESPONSE = DESCRIPTOR.message_types_by_name['Response']
Label = _reflection.GeneratedProtocolMessageType('Label', (_message.Message,), {
  'DESCRIPTOR' : _LABEL,
  '__module__' : 'worker_pb2'
  # @@protoc_insertion_point(class_scope:Label)
  })
_sym_db.RegisterMessage(Label)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSE,
  '__module__' : 'worker_pb2'
  # @@protoc_insertion_point(class_scope:Response)
  })
_sym_db.RegisterMessage(Response)

_WORKER = DESCRIPTOR.services_by_name['Worker']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _LABEL._serialized_start=16
  _LABEL._serialized_end=38
  _RESPONSE._serialized_start=40
  _RESPONSE._serialized_end=65
  _WORKER._serialized_start=67
  _WORKER._serialized_end=131
# @@protoc_insertion_point(module_scope)
